config/routes.rb
Rails.application.routes.draw do
  get "charts/index"
  get "home/index"
  root :to => 'charts#index'
  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #

  resources :charts
  get 'charts/list_products/:filter/:id' => 'charts#list_products', :as => :list_products
end

app/models/chart.rb
class Chart < ApplicationRecord
      validates :name, presence: true,
                length: { minimum: 5 }
      validate :at_least_one_product

      belongs_to :shop
      has_many :chart_details, dependent: :destroy
      has_many :chart_products, dependent: :destroy
      accepts_nested_attributes_for :chart_details, allow_destroy: true
      accepts_nested_attributes_for :chart_products, allow_destroy: true

      validates_associated :chart_details
      validates_associated :chart_products

      private
      def at_least_one_product
        # when creating a new chart: making sure at least one product exists
        return errors.add :base, "Must have at least one Product" unless chart_products.length > 0
    
      end  

end

app/controllers/charts_controller.rb
class ChartsController < AuthenticatedController

  def index
    @charts = Chart.all
  end
  
  def show
    @id = params[:id]
    @chart = Chart.find_by(:id => @id)
    @chart_details = ChartDetail.where(:chart_id => @id)
    @products = ShopifyAPI::Product.find(:all)
    @product_ids = ChartProduct.where(chart_id: @id).select(:product_id).map{|p| p.product_id}
    #@selected_products = ShopifyAPI::Product.find(4290402943029)
    # @selected_products = ShopifyAPI::Product.find(:all, :params => { :id => [4290402943029]})
    @selected_products = @products.select{ |p| @product_ids.include?(p.id.to_s) }
  end


  def destroy
    @id = params[:id]
    @chart = Chart.find_by(:id => @id)
    ActiveRecord::Base.transaction do

    #Cache Old Products & Remove Product Description
    @old_product_ids = ChartProduct.where(chart_id: @chart.id).select(:product_id).map{|p| p.product_id}

    #Clear Products Description
    clearProductsDescription

    #Delete Object
    @chart.destroy

    respond_to do |format|
      format.html { redirect_to '/charts/index', :notice => "Your chart has been deleted !" }
      format.json { head :no_content }
      format.js   { flash[:notice] = 'Chart Deleted Successfully..'  }
    end

    end
    # redirect_to '/charts/index',:notice => "Your chart has been deleted !"

  end


  def list_products
      setProducts(params[:id])
      respond_to do |format|
          format.js { render 'list_products.js.erb'}
      end
  end

  def new
    setProducts(nil)
    @chart = Chart.new
    @chart.chart_details.new
  end

  def create

    #Initialize Params
    @new_params = chart_params
    @chart = Chart.new(chart_params)
    @chart_products = Array.new
    @product_ids = params[:chart_product]
    Array(@product_ids).each do |product_id|
      @chart_product = ChartProduct.new
      @chart_product.product_id = product_id
      @chart.chart_products.push(@chart_product)
    end
    @shop = Shop.find_by(:shopify_domain => ShopifyAPI::Shop.current.domain)
    @chart.shop_id = @shop.id
    
    #Validate Object
    if(!@chart.valid?)
      # Reinitialize Product list Before rendering 
      setProducts(nil)
      render 'new'
      return
    end

    @chart.description = ""

    ActiveRecord::Base.transaction do
    
    #Construct Table
    constructTable

    #Update Product Descriptions
    updateProductsDescription

    if @chart.save
      # @product_ids.each do |product_id|
      #   @chart_products.push({:chart_id => @chart.id, :product_id => product_id})
      # end
      # ChartProduct.create(@chart_products)
      flash[:success] = "Added Successfully !!"
      redirect_to "/charts/index"
    else
            # Reinitialize variables
            setProducts(nil)
            # Render the new page 
            render "new"
    end

  end
  end

  def show
    @id = params[:id]
    @chart = Chart.find_by(:id => @id)
    @chart_details = ChartDetail.where(:chart_id => @id)
    
    #Chart Products
    @products = ShopifyAPI::Product.find(:all)
    @product_ids = ChartProduct.where(chart_id: @id).select(:product_id).map{|p| p.product_id}
    @chart_products = @products.select{ |p| @product_ids.include?(p.id.to_s) }
  end

  def add_chart_detail
    @chart.chart_details.new
  end

  def setProducts(chart_id)
    @products = ShopifyAPI::Product.find(:all)
    @product_ids = Array.new
    @selected_products = Array.new
    if (!chart_id.nil?)
        #Get Product Ids
        @product_ids = ChartProduct.where(chart_id: chart_id).select(:product_id).map{|p| p.product_id}
        
        #Selected Products
        @selected_products = @products.select{ |p| @product_ids.include?(p.id.to_s) }
            #Exclude already added products for other charts
        @assigned_product_ids = ChartProduct.where.not(chart_id: chart_id).select(:product_id).map{|p| p.product_id}
        @products = @products.select{ |p| not @assigned_product_ids.include?(p.id.to_s) }
    else
    
        @assigned_product_ids = ChartProduct.select(:product_id).map{|p| p.product_id}
        @products = @products.select{ |p| not @assigned_product_ids.include?(p.id.to_s) }
    end

  end

  def edit
    @id = params[:id]
    @chart = Chart.find_by(:id => @id)
    @chart_details = ChartDetail.where(:chart_id => @id)

    setProducts(@id)
    if (@id == nil)
      @chart = Chart.new
    end

  end

  def constructTable
       # Construct Table Structure
   @table_structure = "<!-- StartIleanaApp -->"\
   "<script type='text/javascript' src='mydomain.com/widget.js'>\n"\
   "<div style='text-align: center;'' class='ilea-chart'>#{chart_params['name']}</div>\n"\
   "<table style='​display: none;​' width='613' border='0' cellpadding='0' id='ChartNameByUser' class='ileana-chart'>\n"\
   "<thead>\n"\
     "<th>Row Name</th>\n"\
     "<th>#{chart_params['col_1_caption']}</th>\n"\
     "<th>#{chart_params['col_2_caption']}</th>\n"\
     "<th>#{chart_params['col_3_caption']}</th>\n"\
   "</thead>\n"\
   "<tbody>\n"
@chart_details = chart_params['chart_details_attributes']
@chart_details.each do |chart_detail|
@table_structure = @table_structure + "<tr>\n"\
      "<td>#{chart_detail[1]['row_name']}</td>\n"\
      "<td>#{chart_detail[1]['col1']}</td>\n"\
      "<td>#{chart_detail[1]['col2']}</td>\n"\
      "<td>#{chart_detail[1]['col3']}</td>\n"\
      "</tr>\n"
end
@table_structure = @table_structure + "</tbody>\n"
end

def updateProductsDescription
      #Update Description for selected products
      if (!(@product_ids.nil? || @product_ids.empty?))
        @product_ids.each do |product_id|
          @product = ShopifyAPI::Product.find(product_id) 
          if (@product != nil)
              @body_html = @product.body_html
              @script_pos = @body_html.index('<!-- StartIleanaApp -->')
              if (!@script_pos.nil?)
                  @body_html = @body_html.slice(0..(@script_pos-1)) 
              end
                @product.body_html = @body_html + @table_structure
                @product.save
           end
        end
      end
end

def clearProductsDescription
     if (!(@old_product_ids.nil? || @old_product_ids.empty?))

       if (@product_ids.nil?) #Delete
          @removed_product_ids = @old_product_ids
       else
          @removed_product_ids = @old_product_ids - @product_ids
       end

       if (!(@removed_product_ids.nil? || @removed_product_ids.empty?))
          @removed_product_ids.each do |product_id|
            @product = ShopifyAPI::Product.find(product_id)
            if (@product != nil)
                @body_html = @product.body_html
                @script_pos = @body_html.index('<!-- StartIleanaApp -->')
                if (!@script_pos.nil?)
                  @body_html = @body_html.slice(0..(@script_pos-1)) 
                  @product.body_html = @body_html
                  @product.save
                end
             end
          end
        end
      end
end


def update

    ###Initialize
    @chart = find_chart
    @chart.assign_attributes( chart_params)
    @chart_products = Array.new
    @product_ids = params[:chart_product]

    #Cache Old Products & Remove Product Description
    @old_product_ids = ChartProduct.where(chart_id: @chart.id).select(:product_id).map{|p| p.product_id}

    @chart.chart_products.destroy_all
    Array(@product_ids).each do |product_id|
        @chart_product = ChartProduct.new
        @chart_product.product_id = product_id
        @chart.chart_products.push(@chart_product)
    end
    ####

    ###Validate
    if(!@chart.valid?)
        setProducts(@chart.id)
        render 'edit'
        return
    end


    ActiveRecord::Base.transaction do
      #Begin Transaction
      # Update Products Descriptions
      # Update ChartsProducts Table
      # Update Chart Table


   #Construct Table to be inserted into product descriptions
   constructTable

  
    #clearRemovedProductsDescription
    clearProductsDescription

  
    #Update product descriptions
    updateProductsDescription

    #Update ChartProducts Table
    # ChartProduct.where(chart_id: @chart.id).destroy_all
    # ChartProduct.create(@chart_products)

     if @chart.update(chart_params)
        flash[:success] = "Updated Successfully!!"
        render "update"
     else
        setProducts(@chart.id)
        render "edit"
     end

   end # End Transation 
  end



  private
  def chart_params
    params.require(:chart).permit(:name, :col_1_caption, :col_2_caption, :col_3_caption, :is_show_product_page, { chart_details_attributes: ChartDetail.attribute_names.map(&:to_sym).push(:_destroy) })
  end

  private
  def chart_details_params
    params.require(:chart_detail).permit(:row_name, :col1, :col2, :col3)
  end

  def find_chart
    @chart = Chart.find(params[:id])
  end
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/views/charts/_chart_detail_fields.html.erb
<tr class="nested-fields">
  <td><%= f.text_field :row_name, class: 'form-control fields_row_name', :placeholder => "Row Name" %></td>
  <td><%= f.text_field :col1, class: 'form-control fields_col' %></td>
  <td><%= f.text_field :col2, class: 'form-control fields_col' %></td>
  <td><%= f.text_field :col3, class: 'form-control fields_col' %></td>
  <td><%= link_to_remove_association "Delete", f %></td>
</tr>

app/views/charts/_form.html.erb
  <script>
  $(function() {

    $("#forms-container").on("ajax:send", function(){
             $('#spinner').show();
        }
    );

    $("#forms-container").on("ajax:complete", function(){
             $('#spinner').hide();
        }
     );

    }); 
 </script>

  <%= form_with model: @chart, :id=> 'frm' ,:remote => true do  |f| %>

  <div class="row">
    <div class="col-sm-12 col-md-6">
      <div class="card">
        <h5 class="card-header">Chart</h5>
        <div class="card-body">
           <div class="row">
              <div class="col">
                  <label>Chart Name</label>
                  <div>
                    <%= f.text_field :name, class: 'form-control' %>
                  </div>
              </div>
              <div class="col">
                <label>Show link to chart in product page</label>
                <div class="custom-control custom-switch">
                    <%= f.check_box :is_show_product_page, class: 'custom-control-input', :id => 'customSwitch1' %>
                    <label class="custom-control-label" for="customSwitch1">Toggle this switch element</label>
                </div>
              </div>
           </div>
        </div>
      </div>

      <div class="card">
        <h5 class="card-header">Chart</h5>
        <div class="card-body">
          <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col" class='col_row_name'>Row</th>
                <th scope="col">C1</th>
                <th scope="col">C2</th>
                <th scope="col">C3</th>
                <th scope="col"></th>
              </tr>
            </thead>

            <tbody class="chart_details">
                <%= f.fields_for :chart_details do |builder| %>
                    <%= render 'chart_detail_fields', :f => builder %>
                <% end %>
            </tbody>

         </table>
          </div>
          <div class="card-footer links">
                <%= link_to_add_association 'Add Record', f, :chart_details, class: 'btn btn-primary', data: {association_insertion_node: '.chart_details', association_insertion_method: :append} %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-sm-12 col-md-6">
      <div class="card product-list">
        <div class="card-header">
              <h5>Products</h5>
              <h6 class="header-links">
                  <%= link_to image_tag("icon_all.png", border: 0),list_products_path(filter: "all",id:  @chart.id || '0'),class: "list_all_products", remote: true %> 
                  <%= link_to image_tag("icon_selected.png", border: 0),list_products_path(filter: "selected", id: @chart.id || '0'),remote: true %> 
              </h6>
          </div>

        <div class="card-body product-list-panel">
            <%= render 'list_products'%>
        </div>
    </div>
  </div>
  </div>


    <div class="row float-right btns-row">
      <div class="form-group">



        <%= f.submit "Save",remote: true, class: 'btn btn-primary ajax' %>
        <%= link_to 'Back', charts_path, class:'btn btn-primary' %>
        
      </div>
    </div>



  <% end %>

  

app/views/charts/_list_products.html.erb
<script>
  jQuery(function($) {
               $('#txt_search').on('input',function (value) { 
                 console.log('1');
                 var search_txt = this.value.toLowerCase();
                 if (search_txt == '')
                    $(".product-list-item label").parent().css("display","block");
                 else
                    $(".product-list-item label").parent().css("display","none");
                 
                 $( "label" )
                .filter(function( index ) {
                    return $(this).text().toLowerCase().indexOf(search_txt) > -1 ;
                })
                   .parent().css( "display", "block" );
          });
   });
</script>
<% if (params[:filter] == 'all' || params[:filter] == nil ) %>
            <% if (@products != nil) %>
              <div class="form-group has-search product-list-item">
                  <span class="fa fa-search form-control-feedback"></span>
                  <input type="text" class="form-control" placeholder="Search" id='txt_search'>
            </div>
            <% @products.each do |product| %>
              <div class="custom-control custom-checkbox product-list-item">
                    <%= check_box_tag "chart_product[]", product.id, @product_ids.include?(product.id.to_s), id: dom_id(product), class: "custom-control-input" %>
                    <label class="custom-control-label" for=<%= dom_id(product) %>>
                            <img src="<%= product.image.src %>">
                            <%= product.title %>
                    </label>
              </div>
            <% end %>
           <% end %>
          <% else %>
          <% if (@selected_products != nil) %>
            <% @selected_products.each do |product| %>
              <div class="custom-control custom-checkbox product-list-item">
                    <%= check_box_tag "chart_product[]", product.id, @product_ids.include?(product.id.to_s), id: dom_id(product), class: "custom-control-input" %>
                    <label class="custom-control-label" for=<%= dom_id(product) %>>
                            <img src="<%= product.image.src %>">
                            <%= product.title %>
                    </label>
              </div>
            <% end %>
          <% end %>
       <% end %>

app/views/charts/_show.html.erb
  <script>
        $(function() {
            $('#spinner').hide();
        });
  </script>

    <div class="row">
    <div class="col">

  <div class="row">
    <div class="col-6">
      <div class="card">
        <h5 class="card-header">Chart</h5>
        <div class="card-body">
           <div class="row">
              <div class="col">
                  <label>Chart Name</label>
                  <div>
                          <%= @chart.name %>
                  </div>
              </div>
              <div class="col">
                <label>Show link to chart in product page</label>
                <div class="custom-control custom-switch">
                  <%= check_box_tag 'is_show_product_page', @chart.is_show_product_page,@chart.is_show_product_page, options = { class: 'custom-control-input', :id => 'customSwitch1' } %>
                  <label class="custom-control-label" for="customSwitch1">Toggle this switch element</label>
                </div>
              </div>
           </div>
        </div>
      </div>

      <div class="card">
        <h5 class="card-header">Chart</h5>
        <div class="card-body">
          <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Row</th>
                <th scope="col"><%= @chart.col_1_caption %></th>
                <th scope="col"><%= @chart.col_2_caption %></th>
                <th scope="col"><%= @chart.col_3_caption %></th>
              </tr>
            </thead>
            <tbody class="chart_details">
                <% @chart.chart_details.each do |c| %>
                    <tr>
                        <td><%= c.row_name %></td>
                        <td><%= c.col1 %></td>
                        <td><%= c.col2 %></td>                                                
                        <td><%= c.col3 %></td>                        
                    </tr>
                <% end %>
            </tbody>

         </table>
          </div>
        </div>
      </div>

    </div>

    <div class="col-6">

      <div class="card product-list">
        <h5 class="card-header">
              Products
        </h5>

        <div class="card-body">
          <% if (@chart_products != nil) %>
            <% @chart_products.each do |product| %>
              <div class="form-group row product-list-item">
                <div class="col-3">
                    <img src="<%= product.image.src %>" class="mb-2">
                </div>
                <div class="col-6">
                    <%= label_tag dom_id(product), product.title %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>

    </div>

  </div>
  </div>


    <div class="row float-right btns-row">
      <div class="form-group">
        <%= link_to 'Edit', edit_chart_path(@chart), class:'btn btn-primary' %>
        <%= link_to 'Back', charts_path, class:'btn btn-primary' %>
      </div>
    </div>

app/views/charts/create.js.erb
$("#app-notifications").html("");
<% flash.each do |key, value| %>
        $("#app-notifications").append("<div class='alert alert-<%= key %>'><%= value %></div>")
<% end %>
$("html, body").animate({ scrollTop: 0 }, "fast");

app/views/charts/edit.html.erb
<%= render 'form' %>

app/views/charts/edit.js.erb
$("#forms-container").html("<%= j render "form", chart: @chart, products:@products %>");
$("#app-notifications").html("");
<% if @chart.errors.any? %>
    $("#app-notifications").append("<div class='alert alert-error'><h6>Please resolve the following errors:</h6><ul id='error-list'>");
    <% @chart.errors.full_messages.each do |msg| %>
                        $("#error-list").append("<li><%= msg %></li>");
    <% end %>
    $("#app-notifications").append("</ul></div>");
<% else %>
        <% flash.each do |key, value| %>
                $("#app-notifications").append("<div class='alert alert-<%= key %>'><%= value %></div>")
        <% end %>
<% end %>
$("html, body").animate({ scrollTop: 0 }, "fast");

app/views/charts/index.html.erb
<script>
  $(function() {
    $("#forms-container").on("ajax:send", function(){
             $('#spinner').show();
        }
    );

    $("#forms-container").on("ajax:complete", function(){
             $('#spinner').hide();
        }
     );

    }); 
</script>

  <div class="row">
    <div class="col-sm-12 col-md-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Build your first Chart !</h5>
          <p class="card-text">Follow the guidelines,, Follow the guidelines,, Follow the guidelines ,, Follow the guidelines</p>
          <a href="#" class="btn btn-primary">Get Started !</a>
        </div>
      </div>
    </div>

    <div class="col-sm-12 col-md-6">
      <div class="card charts-list">
        <div class="card-header">
          Charts
        </div>

        <div class="card-body">
          <% if @charts.count == 0 %>
            <p class="card-text">
            <h5 class="card-title">You have not created any charts yet !</h5><br>
            Click on <b>Get Started</b> .. to get started. You can choose which products use each other </p>
          <% else %>
            <% @charts.each do |chart| %>
              <div class="chart-list-item row">
                <div class="col-8 card-record-title"> <%= link_to chart.name, chart_path(chart) %> </div>
                <div class="col card-record-actions">
                  <%= link_to image_tag("icon_edit.png", :border=>0, :class => 'list-icons'), edit_chart_path(chart), local: true %>
                  <%= link_to image_tag("icon_delete.png", :border=>0, :class => 'list-icons'), chart_path(chart), method: "delete",remote: true,:class => "delete_chart", data: { confirm: "Are you sure?", disable_with: "Processing..." } %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>


    </div>

  </div>

app/views/charts/list_products.js.erb
$(".product-list-panel").html("<%= j render 'list_products', locals: {products: @products}  %>")

app/views/charts/new.html.erb
<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<%= render 'form' %>

app/views/charts/new.js.erb
$("#forms-container").html("<%= j render "form" %>");
$("#app-notifications").html("");
<% if @chart.errors.any? %>
    $("#app-notifications").append("<div class='alert alert-error'><h6>Please resolve the following errors:</h6><ul id='error-list'>");
    <% @chart.errors.full_messages.each do |msg| %>
                        $("#error-list").append("<li><%= msg %></li>");
    <% end %>
    $("#app-notifications").append("</ul></div>");
<% else %>
        <% flash.each do |key, value| %>
                $("#app-notifications").append("<div class='alert alert-<%= key %>'><%= value %></div>")
        <% end %>
<% end %>
$("html, body").animate({ scrollTop: 0 }, "fast");

app/views/charts/show.html.erb
<%= render 'show' %>

app/views/charts/show.js.erb
$('#forms-container').empty().append("<%= j render 'show' %>")

app/views/charts/update.js.erb
$("#app-notifications").html("");
<% if @chart.errors.any? %>
    $("#app-notifications").append("<div class='alert alert-error'><h6>Please resolve the following errors:</h6><ul>");
              <% @chart.errors.full_messages.each do |msg| %>
                        $("#app-notifications").append("<li><%= msg %></li>");
              <% end %>
    $("#app-notifications").append("</ul></div>");
<% else %>
        <% flash.each do |key, value| %>
                $("#app-notifications").append("<div class='alert alert-<%= key %>'><%= value %></div>")
        <% end %>
<% end %>    
$("html, body").animate({ scrollTop: 0 }, "fast");